[package]
name = "uspto"
version = "0.1.0"
authors = ["Walther Chen <walther.chen@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
snafu = "0.4.3"
serde-xml-rs = "0.3.1"
xml-rs = "0.8.0"
